#!/usr/bin/env bash

echo "Installing Docker Engine"

# Docker dependency in case it is not already installed
sudo dnf -y install dnf-plugins-core -y

# Adding the repo
sudo dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

# Install Docker engine and helper packages
sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

# Create the docker group
sudo groupadd docker

# Add your user to the docker group
sudo usermod -aG docker $USER

newgrp docker

